/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./src/components/layouts/BaseSide.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logos: typeof import('./src/components/Logos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
